/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ClienteFactory;
import controle.OrdemServFactory;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import modelo.bean.Cliente;
import modelo.bean.OrdemServico;

/**
 *
 * @author bruno
 */
public class ConsOrdemServico extends javax.swing.JFrame {

    /**
     * Creates new form ConsOrdemServico
     */
    private int idUsuario;
    
    public ConsOrdemServico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de ordens de serviço");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número", "Cliente", "Carro", "Peça", "Data abertura", "Data encerramento", "Prazo de entrega", "Peça trocada", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTable2ComponentShown(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable2ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2ComponentShown

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        OrdemServFactory osf = new OrdemServFactory();
        int idCliente = 
            ((Cliente) (new ClienteFactory()
                .consultar("from Cliente where idUsuario = " + this.idUsuario)).get(0)).getId();
        
        List<Object> list = osf.consultar("from OrdemServico where idCliente = "+idCliente+" and status = 0");
        String colunas[] = {"Número", "Cliente", "Carro", "Peça", "Data abertura", 
            "Data encerramento", "Prazo de entrega", "Peça trocada", "Status"};
        DefaultTableModel modelo = new DefaultTableModel(colunas, 0);
        
        for (int i = 0; i < list.size(); i++) {
            String status = "";
            String dtEncerramento = "";
            String pecTrocada = "Não";
            
            if (((OrdemServico) list.get(i)).getStatus() == 0) 
               status = "Em execução";
            
            if (((OrdemServico) list.get(i)).getDtEncerramento() != null) 
               dtEncerramento = ((OrdemServico) list.get(i)).getDtEncerramento().toString();
            
            if (((OrdemServico) list.get(i)).isPecaTrocada())
               pecTrocada = "Sim";
            
            modelo.addRow(new String[]{
                ((OrdemServico) list.get(i)).getNumero().toString(), 
                ((OrdemServico) list.get(i)).getCliente().getNome(), 
                ((OrdemServico) list.get(i)).getCarro().getNome(),
                ((OrdemServico) list.get(i)).getPeca().getNome(),
                ((OrdemServico) list.get(i)).getDtAbertura().toString(),
                dtEncerramento,
                ((OrdemServico) list.get(i)).getPrazoEntrega().toString(),
                pecTrocada,
                status});
        }
        jTable2.setModel(modelo);
    }//GEN-LAST:event_formWindowOpened

    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}